vpc_id             = "vpc-0e3e21ae98b3cf52b"
vpc_cidr           = "172.31.0.0/16"
subnet_ids         = ["subnet-0e1914fc24b7287af"]
sftp_users         = { internet = "internet" } # username is internet and home directory is also internet(inside the S3 bucket)
#Form Multiple users
#sftp_users={
#    "dev" = "dev"
#    "qa" = "qa"
#    "ci" = "ci"
#  }
#here interrnet is the username and given is the public key generated by ssh-keygen
sftp_users_ssh_key = { internet = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQ4srCgVhnu6AfbHWAjPkFwrkLBi+XBpvnvTBCpVDpieCvf7MXtMD3HSjB0Qxdezuk+ZzxmO5B3pKG+O1o4Ak1cZvQ1WoTwuW5zl7RmMJ4cdoG87grXCH5zXlbu2FWIYKgRMqwgMZ1ob7HW71wIz/MM4VyvwQ3t4jNTNGYZsidCqHroDQBybVvRU3ts4VSxpp9hNRVynY0oZVg40ojw2ONgfcfM7rUeNWVVGN/1+Tf3G6hk0kwuo6Lojqdna3hSp9QW0wIWOxz0U2PslyuiC0CziLn4xftbSE7WqmRkqbVI5J3jLKGI/4e69brLFBFQbZX63yMjtrlEJJQ8D/vcJ7YRp841PFKP+5Q8imNkr5MfrR9ZiD55dKyyIgwh14z5dhUKtNlxYQhPzQGeYS+IzceYW0j1lOlg8VO8YuRcAG9qs7Ok3g3WC9p0kJEsQ3O3GA9ufWbkatIPeB6ThWQc9OV+EAikZk+vh2Vgg5LiC3n4i/PQ52QAZG6fIb4RNgSI4s"
}
